const pict = require('../lib/pict').pict;
const assert = require('assert');

describe('pict - model validation', () => {
  it('returns errors generated by PICT', () => {
    let result = pict({
      parameters: [
        { property: 'Size', values: [10, 100, 500, 1000, 5000, 10000, 40000] },
        { property: 'Format method', values: ['quick', 'slow'] },
        { property: 'Format method', values: ['quick', 'slow'] },
        { property: 'File system', values: ['FAT', 'FAT32', 'NTFS'] },
      ],
    });

    assert.match(
      result.command,
      /Command failed: .\/binaries\/pict.*_generated.model/
    );
    assert.strictEqual(
      result.error,
      'Input Error: A parameter names must be unique'
    );
  });
});
